### ISSUE TITLE
Conflict of class name and member function?

### ISSUE THREAD

**Issue by sampsongao** [nodejs/node-api#11]
Seeing these errors on linux. Consider changing the member function name to be Env GetEnv()/Arraybuffer GetArrayBuffer, or changing return types to be Napi::Env Env() and Napi::ArrayBuffer ArrayBuffer().

../node_modules/napi/napi.h:90:15: error: declaration of ‘Napi::Env Napi::Value::Env() const’ [-fpermissive]
     Env Env() const;
               ^
../node_modules/napi/napi.h:58:9: error: changes meaning of ‘Env’ from ‘class Napi::Env’ [-fpermissive]
   class Env {
         ^
../node_modules/napi/napi.h:270:31: error: declaration of ‘Napi::ArrayBuffer Napi::TypedArray::ArrayBuffer() const’ [-fpermissive]
     ArrayBuffer ArrayBuffer() const;
                               ^
../node_modules/napi/napi.h:240:9: error: changes meaning of ‘ArrayBuffer’ from ‘class Napi::ArrayBuffer’ [-fpermissive]
   class ArrayBuffer : public Object {
         ^

**Comment by jasongin** [comment]
I'd rather not change the names. These just need a namespace prefix to make the compiler happy, for example:

```C++
Napi::Env Env()
```
