### ISSUE TITLE
_NOEXCEPT or noexcept

### ISSUE THREAD

**Issue by sampsongao** [nodejs/node-api#12]
The keyword seems to be "noexcept" on linux.

../node_modules/napi/napi.h:452:24: error: expected ‘;’ at end of member declaration
     const char* what() const _NOEXCEPT override;
                        ^
../node_modules/napi/napi.h:452:30: error: ‘_NOEXCEPT’ does not name a type
     const char* what() const _NOEXCEPT override;
                              ^

**Comment by jasongin** [comment]
Hmm, I'm pretty sure this worked when I built with GCC on macOS.

Anyway, we need to figure out a cross-platform way to do this. I don't think `noexcept` will work everywhere.

**Comment by gabrielschulhof** [comment]
#ifdef?

**Comment by sampsongao** [comment]
Do ou mean
```
#ifndef _NOEXCEPT
  #define _NOEXCEPT noexcept
#endif
```

**Comment by gabrielschulhof** [comment]
Yeah, or something platform-based.
