### ISSUE TITLE
Exception handling disabled and adding "'cflags_cc': ['-fexceptions']" in binding.gyp doesn't solve it.

### ISSUE THREAD

**Issue by sampsongao** [nodejs/node-api#13]
Not sure if I am missing something here. What else should I do to enable exception handling in module?

../node_modules/napi/napi-inl.h: In function ‘void Napi::RegisterModule(napi_env, napi_value, napi_value, void (*)(Napi::Env, Napi::Object, Napi::Object))’:
../node_modules/napi/napi-inl.h:40:23: error: exception handling disabled, use -fexceptions to enable
   catch (const Error& e) {
                       ^

**Comment by jasongin** [comment]
Did you follow the instructions about enabling exceptions in the [README](https://github.com/nodejs/node-api/blob/master/README.md)?

**Comment by sampsongao** [comment]
That is not working for some reason.

**Comment by jasongin** [comment]
Can you share a link to your `binding.gyp`?

**Comment by sampsongao** [comment]
https://github.com/sampsongao/node-nanomsg/blob/napi-wrapper-port-3.2.4/binding.gyp

**Comment by jasongin** [comment]
The cflags settings you added are not taking effect because they are inside a conditional block with the condition `use_system_libnanomsg=="true"`, but that variable defaults to false.

**Comment by sampsongao** [comment]
Thanks, moving it into the use_system_libnanomsg=="false" block works.
