### ISSUE TITLE
Symbol class missing

### ISSUE THREAD

**Issue by sampsongao** [nodejs/node-api#16]
Are we using String class for both string and symbol use cases?

**Comment by jasongin** [comment]
There should definitely be a `Napi::Symbol` class.

Feel free to make PRs. :)

**Comment by jasongin** [comment]
Also a `Napi::Name` class that is a common base class for `Symbol` and `String`, because there are several APIs that can accept either a string or symbol.

**Comment by jasongin** [comment]
Added with https://github.com/nodejs/node-api/pull/27
