### ISSUE TITLE
Function::New ambiguity

### ISSUE THREAD

**Issue by sampsongao** [nodejs/node-api#17]
```
error: call of overloaded ‘New(Napi::Env&, Napi::Value (&)(const Napi::CallbackInfo&))’ is ambiguous
     Napi::Function::New(env, S));
                               ^
```

**Comment by jasongin** [comment]
What is the code that produced this error message?

**Comment by jasongin** [comment]
> New(Napi::Env&, 

You must be using an older version of the code. In the latest version, the type of the `env` parameter is `napi_env`. I don't know if that is related to the error though.

**Comment by sampsongao** [comment]
I guess it just the compiler is confused about which of the four Napi::Function::New it should be using.

**Comment by jasongin** [comment]
Yes, but it shouldn't get confused unless the type of `S` is not exactly one of the allowed callback types.

**Comment by addaleax** [comment]
I *think* this would be fixed by 52c1aa9.

**Comment by addaleax** [comment]
@sampsongao can you check whether this is still a problem with the current `master`? If not, I agree with @jasongin, it would be good to have a bit more context around that error message.

**Comment by jasongin** [comment]
@sampsongao Is this still an issue?

**Comment by sampsongao** [comment]
I don't see the error message. It should to be fixed.
