### ISSUE TITLE
N-API Documentation not present in "View on single page"

### ISSUE THREAD

**Issue by ealib** [nodejs/node-api#35]
If you click on [View on single page"](https://nodejs.org/dist/latest-v7.x/docs/api/all.html) from [N-API](https://nodejs.org/dist/latest-v7.x/docs/api/n-api.html), then **N-API** chapter is *not* present.

**Comment by addaleax** [comment]
Yeah, there’s a weird bug – the N-API docs should not be there anyway yet, see https://github.com/nodejs/node/issues/12833

**Comment by ealib** [comment]
Thanks. I see it was fixed with #12957.
